### ISSUE TITLE
Auto-open magnet on torrent download

### ISSUE THREAD

**Issue by jrejaud** [jingnanshi/KickassScrapper#4]
Hi there,

Is the script supposed to also open a magnet file when it is selected, or does it just display the magnet link in the console?

**Comment by jingnanshi** [comment]
Hi,

The script will display the magnet link in the console. If you use the file
option, it will save the torrents down to your folder of choice.

On Wed, Apr 6, 2016 at 10:12 PM, Jordan Réjaud notifications@github.com
wrote:

> Hi there,
> 
> Is the script supposed to also open a magnet file when it is selected, or
> does it just display the magnet link in the console?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jingnanshi/kickass-get/issues/4

## 

Jingnan Shi
Engineering & Mathematics
Harvey Mudd College

**Comment by jrejaud** [comment]
Ok, is there also a parameter to have it automatically open the magnet link
url (using whatever the default program on your computer is for such
things)?

Cheers,
Jordan Rejaud, EIT
M.S. Carnegie Mellon
jordanrejaud.com

**Comment by jingnanshi** [comment]
Hi,

Just merged your pull request. Awesome!

On Thu, Apr 7, 2016 at 8:25 AM, Jordan Réjaud notifications@github.com
wrote:

> Ok, is there also a parameter to have it automatically open the magnet link
> url (using whatever the default program on your computer is for such
> things)?
> 
> Cheers,
> Jordan Rejaud, EIT
> M.S. Carnegie Mellon
> jordanrejaud.com
> On Apr 6, 2016 11:03 PM, "Jingnan Shi" notifications@github.com wrote:
> 
> > Hi,
> > 
> > The script will display the magnet link in the console. If you use the
> > file
> > option, it will save the torrents down to your folder of choice.
> > 
> > On Wed, Apr 6, 2016 at 10:12 PM, Jordan Réjaud <notifications@github.com
> > 
> > wrote:
> > 
> > > Hi there,
> > > 
> > > Is the script supposed to also open a magnet file when it is selected,
> > > or
> > > does it just display the magnet link in the console?
> > > 
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/jingnanshi/kickass-get/issues/4
> > 
> > ## 
> > 
> > Jingnan Shi
> > Engineering & Mathematics
> > Harvey Mudd College
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/jingnanshi/kickass-get/issues/4#issuecomment-206708664>
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/jingnanshi/kickass-get/issues/4#issuecomment-206952225

## 

Jingnan Shi
Engineering & Mathematics
Harvey Mudd College

**Comment by jrejaud** [comment]
Awesome :)

Great script btw, very useful

Cheers,
Jordan Rejaud, EIT
M.S. Carnegie Mellon
jordanrejaud.com
